<a href="https://colab.research.google.com/github/BlitzKingFr/ML-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Numpy

In [4]:
import numpy as np

In [10]:
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [18]:
even = np.arange(0,20,2)#(start,end,step)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
odd = np.arange(1,20,2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [11]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
even + odd

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37])